const LOGICAL_NUMBER_FACEBOOK = "FB";
const LOGICAL_NUMBER_GOOGLE = "GOOGLE";
const LOGICAL_NUMBER_LOGINDEFAULT = "LOGINDEFAULT";

export const TYPE_LOGIN = {
  LOGICAL_NUMBER_FACEBOOK,
  LOGICAL_NUMBER_GOOGLE,
  LOGICAL_NUMBER_LOGINDEFAULT,
};
